fragforce/pages/events/2016/04/Herndon.html
fragforce/templates/events/page.html
fragforce/views/pages.py

Added youtube video embed to event page template

Added Herndon 2016 kickoff event details

---

fragforce/pages/events/2016/11/Portland.html

Adding Fragforce PDX

---

fragforce/pages/events/2016/11/Portland.html

Activating Fragforce PDX

---

.gitignore
fragforce/pages/blog/2016/09/ucsf_networking_plan.html

New blog entry on UCSF networking plans

New Blog Entry Draft

---

fragforce/templates/base.html
fragforce/templates/layouts/progress-left.html
fragforce/templates/layouts/social.html
fragforce/templates/tracker.html

- Add automatic HTML5 refresh to tracker

Move column definitions to base class

---

fragforce/pages/events/2016/09/Tabletop.html

Tabletop appreciation day page pull request

---

fragforce/pages/events/2016/09/Tabletop.html

age
pull it!
pull it!!!!!!!!one!

whatever you wanna put for pull commit change mess

---

fragforce/templates/layouts/head.html
fragforce/templates/layouts/js_bottom.html

Fixes the dropdown menu functionality at small
browser sized

Moved jquery js import to correct location

---

fragforce/pages/events/2016/11/Herndon.html
run.py

Also refactor run.py because optparse is deprecated.

Add the November Herndon event with Child's Play info

---

fragforce/pages/events/2016/11/Herndon.html

@AevumDecessus Don't merge this until morning; I'll probably have more changes.

Misc Herndon Event Changes - Nov 4th/5th

---

fragforce/__init__.py

and modifying Childs Play URL for team signpu

Removing % from tiltify json data

---

app.json

theoretically enables automatic PR builds in heroku

Added basic app.json

---

fragforce/__init__.py
fragforce/cron.py
fragforce/views/general.py

New config variables per #124 
Fixed broken fw backup.xml generation in heroku

Added new config variables, fixed fw backup.xml

---

fragforce/templates/general/join.html

Fixed typos

---

fragforce/__init__.py

Updating the Token for the FY19 Tiltify campaign

Updating __init__.py Tiltify token

---

fragforce/pages/events/2017/11/Dublin.html

Adding Fragforce Dublin November event

---

fragforce/templates/general/donate.html

Adding https://tiltify.com/+fragforce/fragforce-fy19 for the updated FY19 link

Updating tiltify campaign

---

fragforce/templates/general/index.html

Added https://tiltify.com/+fragforce/fragforce-fy19 to the donation campaign

Updating FY19 references

---

fragforce/templates/general/donate.html

Fixing FY18 to FY19

---

fragforce/templates/layouts/header.html

twitch.tv/fragforce is the new link

Updated Twitch link

---

fragforce/pages/events/2018/03/Dublin.html
fragforce/templates/general/join.html

It's picking up some other commit not merged that fixes some typos, so I am sending it along 
@rev @R0ot2U

Adding Dublin March Event 

---

fragforce/pages/events/2018/03/Dublin.html

Dublin event in March - Adding Boardgames info

---

fragforce/__init__.py
fragforce/static/js/common.js
fragforce/templates/events/by_sfid.html
fragforce/templates/events/site.html
fragforce/templates/layouts/footer.html
fragforce/templates/layouts/head.html

```
Site: Fragforce Colorado
Start: Fri Jul 20 2018 14:00:00 GMT-0400 (Eastern Daylight Time)
End: Fri Jul 20 2018 15:00:00 GMT-0400 (Eastern Daylight Time)
```
Example: https://fragforce-dev-paulson.herokuapp.com/sites/0014100001NIUp1AAH/

Timezone Fix For Events

---

ffsite/templates/ff/root/join.html

Updated url to https://tiltify.com/+fragforce/

Updated the tiltify campaigns

---

ffdonations/views/donations.py

Testing order by URL on donations page - hold for now, until this is confirmed working

Order By Changes - Donations

---

ffsite/static/ffsite/overlays/event_total.html

Shows total amount raised by the team, minus a startAmount value

Added event_total.html overlay page

---

extralifeapi/participants.py

The `update_participants` task was generating errors in el/participants.py during field type conversion. This resolves that problem.

Fixing `update_participants` Bug

---

ffsite/static/ffsite/images/dice.svg
ffsite/templates/ff/base.html

 Changed icon to svg

---

Dockerfile
Pipfile
Pipfile.lock
docker-compose.yml

Created dockerfile and docker-compose to run dev commands like django DB migrations from

Docker env

---

ffstream/admin.py
ffstream/views.py

* Added search fields to admin for ffstream
* Fixed typo in views for ffstream

Added livestream to admin view

---

fforg/settings.py

Also fix timedeltas to match the units of the variable names

Fix defaults to only query every 15s

---

ffdonations/utils.py

Actually check all tracked teams for donation totals
Don't double-sum participant and team donations

Utils cleanup

---

ffsite/templates/ff/root/donate.html
ffsite/utils.py

previously this pulled from every contact in the org DB

Change random_contact to only pull from active

---

Dockerfile.beat
Dockerfile.web
Dockerfile.worker

chown the files copied in
run collectstatic

Tweaks to dockerfiles

---

fforg/settings.py

containers are all on internal docker loopbacks, no SSL between them

Tweak psql connections for docker production

---

.github/workflows/dev-images.yaml
.github/workflows/prod-images.yaml

Set output image to REPOSITORY_OWNER
